NotesWeb/Models/FilterViewModel.cs
using System;

namespace NotesWeb.Models
{
    public class FilterViewModel
    {
        public Importance Importance { get; set; }
        public ClassType ClassType { get; set; }
        public DateTime Date { get; set; }
    }
}

NotesWeb/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;


namespace NotesWeb.Models
{
    public class Note
    {
        [Key] public int NoteId { get; set; }
        public string Name { get; set; }
        public Category Category { get; set; }
        public string Text { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }

    }
}

NotesWeb/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NotesWeb.Models;
using System.Diagnostics;
using Microsoft.AspNet.Identity;
using NotesWeb.Services.DataBaseServices;
using NotesWeb.Services.InterfaceService;
using System.IO;

namespace NotesWeb.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private NotesContext db = new NotesContext();
        private INoteService _noteService = new NoteDbService();
        

        // GET: Notes
        public ActionResult Index(bool filt = false)
        {
            if (filt)
            {
                var list = TempData["notes"] as List<Note>;
                ViewBag.Message = "Filter results:";
                return View(list);
            }
            else
            {
                var noteList = _noteService.SelectAllForUser(User.Identity.GetUserId());
                ViewBag.Message = "";
                return View(noteList);
            }
        }

        // GET: Notes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Include(n => n.Attachments).SingleOrDefault(n => n.NoteId == id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // GET: Notes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NoteId,Name,Category,Text,CreationDate,UpdateDate")] Note note)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId()) as User;
                note.Users = new List<User>();
                note.Users.Add(user);
                note.CreationDate = DateTime.Now;
                note.UpdateDate = DateTime.Now;
                db.Notes.Add(note);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(note);
        }

        public ActionResult Upload(int id)
        {
            Note note = db.Notes.Find(id);
            return View(note);
        }

        [HttpPost]
        public ActionResult Upload(int id,HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var at = new Attachment();
                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                {
                    at.Picture = reader.ReadBytes(upload.ContentLength);
                }
                var note = db.Notes.Find(id);
                if (note.Attachments == null) note.Attachments = new List<Attachment>();
                note.Attachments.Add(at);
                note.UpdateDate = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult GetImg(int id)
        {
            Attachment at = db.Attachments.Find(id);
            return File(at.Picture, "image/jpg");
        }

        // GET: Notes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NoteId,Name,Category,Text,CreationDate")] Note note)
        {
            if (ModelState.IsValid)
            {
                note.UpdateDate = DateTime.Now;
                db.Entry(note).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _noteService.Delete(id);
            //Note note = db.Notes.Find(id);
            //db.Notes.Remove(note);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Filter()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Filter(Category c)
        {
            if (ModelState.IsValid)
            {
                Importance imp = c.Importance;
                ClassType ct = c.ClassType;
                var noteList = _noteService.SelectAllForUser(User.Identity.GetUserId());
                var list = noteList.Where(n => (n.Category.Importance == imp) && (n.Category.ClassType == ct)).ToList();
                TempData["notes"] = list;
                return RedirectToAction("Index", new { filt = true });
            }

            return View();
        }
    }
}

NotesWeb/Views/Notes/Create.cshtml
@model NotesWeb.Models.Note

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(m => m.Category.Importance, null, new { @class = "form-control" })
                @Html.EnumDropDownListFor(m => m.Category.ClassType, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, 10, 80, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotesWeb/Views/Notes/Delete.cshtml
@model NotesWeb.Models.Note

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NotesWeb/Views/Notes/Details.cshtml
@model NotesWeb.Models.Note

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

    </dl>
</div>
@foreach (var img in Model.Attachments)
{
    <td>
        <img src="@Url.Action("GetImg", new { id = img.AttachmentId })" width="300" height="210" />
    </td>
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NoteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NotesWeb/Views/Notes/Edit.cshtml
@model NotesWeb.Models.Note

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NoteId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(m => m.Category.Importance, null, new { @class = "form-control" })
                @Html.EnumDropDownListFor(m => m.Category.ClassType, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, 10, 80, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CreationDate)
                @Html.DisplayFor(model => model.CreationDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.UpdateDate)
                @Html.DisplayFor(model => model.UpdateDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotesWeb/Views/Notes/Filter.cshtml
@model NotesWeb.Models.Category

@{
    ViewBag.Title = "Filter";
}

<h2>Filter</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="row">
            <div class="col-xs-2">
                <label>Choose importance</label>
                @Html.EnumDropDownListFor(m => m.Importance, null, new { @class = "form-control" })
            </div>
            <div class="col-xs-2">
                <label>Choose class type</label>
                @Html.EnumDropDownListFor(m => m.ClassType, null, new { @class = "form-control" })
            </div>
        </div>

    </div>

    <input type="submit" value="Filter" class="btn btn-primary" />
}

NotesWeb/Views/Notes/Index.cshtml
@model IEnumerable<NotesWeb.Models.Note>

@{
    ViewBag.Title = "Index";
}

<h2>My notes</h2>

<p>
    @Html.ActionLink("Create New", "Create", "", new { @class = "btn btn-primary" })
</p>
<p>
    @Html.ActionLink("Filter", "Filter", "", new { @class = "btn btn-primary" })
</p>

<h3>@ViewBag.Message</h3>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NoteId }) |
            @Html.ActionLink("Add image", "Upload", new { id=item.NoteId}) |
            @Html.ActionLink("Display", "Details", new { id=item.NoteId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NoteId })
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

NotesWeb/Views/Notes/Upload.cshtml
@model NotesWeb.Models.Note

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>

@using (Html.BeginForm("Upload", "Notes", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Attachment", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Picture" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group">
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}